# Parameters of the point robots for behavior simulation
# basic_rules:  # Uncomment this if launching the basic_rules_launch.py file 
extended_rules:  
  ros__parameters:
    # General params
    mass: 1.0   # mass of the point robot
    max_acc: 3.0 
    max_speed: 0.15
    min_dist: 0.3   # minimum distance between point robots for flocking - [twice the size of half a robot, plus one robot]
    min_dist_to_obst: 0.5
    w_flocking: 0.08   # 3.
    w_navigation: 0.05   # 2. 
    w_obst_avoid: 0.1   # 1.
    # order for PAA - [1: Obstacle avoidance, 2: Navigation to a point, 3: Basic flocking]
    order: '123' # string of desired behavior priority order for velocity combination
    
    num_robots: 10
    neigh_radius: 0.7   # radius around each robot to check for neighbours
    fov_deg: 270      # angle of fov in degrees
    w_separation: 1.0  
    w_alignment: 0.7 
    w_cohesion: 0.6
    publish_rate: 10.0   # in Hz, for control timer

    # Params for Extended rules (Navigation)
    target_x: 3.5
    target_y: 3.5
    slowing_distance: 1.0  # for arrival behavior 

    # Params for Extended rules (Obstacle avoidance)
    lookahead_distance: 2.5
    robot_radius: 0.2


    
    

    
